name: Build and deploy ASP.Net Core app to Azure Web App - backend-blog-post-rest-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore Blog.Post.Manager.Backend/Blog.Post.Manager.Backend.Api/Blog.Post.Manager.Backend.Api.csproj

      - name: Build with dotnet
        run: dotnet build --configuration Release --no-restore Blog.Post.Manager.Backend/Blog.Post.Manager.Backend.Api/Blog.Post.Manager.Backend.Api.csproj

      - name: Publish the application
        run: dotnet publish -c Release --no-build -o "${{ github.workspace }}/publish" Blog.Post.Manager.Backend/Blog.Post.Manager.Backend.Api/Blog.Post.Manager.Backend.Api.csproj

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{ github.workspace }}/publish

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # Required for requesting JWT
      contents: read  # Required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_CBCFC8C6B49F48498ABB8462FE852C14 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_61E9E9A8DDF246C2BA85563F9F013122 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_442C207D27454B839F93414B8123D629 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'backend-blog-post-rest-api'
          slot-name: 'Production'
          package: .
